### PR TITLE
Added download progress bar for CIFAR-10

### PR DESCRIPTION
**Pull request by Mithil467**
CIFAR-10 binary is about 162 MB in size. Downloading it can take a long time. A download progress bar can really be helpful.

### CODE REVIEW

**Comment by prabhuomkar** [comment]
@Mithil467 your branch appears to be stale. Please pull the latest changes from master branch into your branch.

**Comment by mfl28** [comment]
Hi @Mithil467 
When I wrote these files I added the '...' to 'Fetching CIFAR10' etc. to indicate that this takes some time, but I can see why it might be preferable to have the progress shown explicitly :). So thanks for adding the change!

@prabhuomkar 
It works on Windows 10 as well. However, I am not so sure if we should add the progress bar to the other smaller datasets. For example for MNIST, 4 files are downloaded, each of which would have its own progress output, which might be a bit too verbose, don't you think?

**Comment by prabhuomkar** [comment]
@mfl28 I agree with its nature and will be an overkill. I think its good if there was a dynamic progress bar for CMake. Anyways, I think this solves the purpose; as CIFAR10 being the only bulky dataset in our tutorial as of now.

**Comment by prabhuomkar** [comment]
This closes #42

**Pull request merged**
